Task 1
iakkivr/TestGuru pull request #3
Opened 2022-04-22 20:51 UTC by iakkivr

2022-04-24 11:30 UTC, VidgarVii requested changes

2022-04-24 11:30 UTC, VidgarVii commented on README.md
> +* Вопросы
замечание тот же https://github.com/iakkivr/TestGuru/pull/1#discussion_r856010887

2022-04-24 11:30 UTC, VidgarVii commented on app/views/author/author.html
> +</html>
по моему я уже писал
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-04-24 11:30 UTC, VidgarVii commented on app/views/author/author.html
> +<body>
пустой файл. нет содержимого

2022-04-24 11:30 UTC, VidgarVii commented on app/views/author/author.html
> +<!DOCTYPE html>
не верный путь к файлу. Он должен открываться по пути /about/author

2022-04-24 11:30 UTC, VidgarVii commented on app/views/author/author.html
> +<html lang="en">
локаль не совпадает с настройками проекта

2022-04-24 11:30 UTC, VidgarVii commented on config/routes.rb
> +  get 'about/author', :to => redirect('/author.html')
статичные файлы из папки паблик минуют контроллеры, роуты и пр.
Данная запись говорит о том, что просто не верно были прописаны пути в файлах и эта настройка является лишней. Редирект используется не корректно. Является костылём

2022-04-24 11:30 UTC, VidgarVii commented on public/author.html
> +<!DOCTYPE html>
так вот он где
тогда этот app/views/author/author.html файл надо удалить и исправить путь к файлу.
Если файл положить в папку public/about/ то файл будет открываться корректно без всяких редиректов

2022-04-25 16:14 UTC, VidgarVii requested changes

2022-04-25 16:14 UTC, VidgarVii commented on README.md
> +* Вопросы
не хватает сущности для записи результата пройденных тестов

2022-04-25 16:14 UTC, VidgarVii commented on public/about/author.html
> +<html lang="en">
https://github.com/iakkivr/TestGuru/pull/3#discussion_r857111082
и не совпадает с содержимым страницы

2022-04-25 16:14 UTC, VidgarVii commented on app/views/author/author.html
> +<!DOCTYPE html>
не удалил не нужный файл

2022-04-25 16:19 UTC, iakkivr commented on app/views/author/author.html
> +<!DOCTYPE html>
Какой имеется ввиду? У меня сейчас два файла добавлены. Public/about.html И Public/about/author.html

2022-04-26 12:27 UTC, merged