Task 3
iakkivr/TestGuru pull request #5
Opened 2022-05-01 09:10 UTC by iakkivr

2022-05-01 18:59 UTC, BubuntuClu requested changes

2022-05-01 18:59 UTC, BubuntuClu commented on app/models/test.rb
> +    by_category(category).order(title: :desc).pluck(:title)
откуда метод `by_category`? не вижу его реализации

2022-05-01 18:59 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where(level: level)
что такое `tests`? в модели нет ничего что определяет этот объект/метод

2022-05-01 18:59 UTC, BubuntuClu commented on db/seeds.rb
> +  category_id = (1..4).to_a.sample
это ненадежный способ. при нескольких накатах сида в БД, может сдвинуться последовательность id в таблицах и тогда твой поиск 1-4 не будет работать.
сохраняй созданные объекты в массив и используй этот массив при создании зависимых объектов. это относится ко всем операциям ниже

2022-05-02 17:04 UTC, BubuntuClu requested changes

2022-05-02 17:04 UTC, BubuntuClu commented on app/models/test.rb
> +    category_id = Category.where(title: category).take&.id
ты знаешь операцию `join` из SQL. надо ее тут использовать, чтобы получить нужные данные за один запрос к БД

2022-05-02 17:04 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(author_id: id, level: level)
этот запрос будет искать тесты, созданные каким-то пользоватем, а по заданию надо найти тесты, которые пользователь проходил. для этого тебе потребуется промежуточная таблица, так как надо реализовать связь многие-ко-многим

2022-05-02 17:04 UTC, BubuntuClu commented on db/seeds.rb
> +  author_id = User.pluck(:id).sample
это будет делать запросы к БД, чтобы получить данные, которые ты создал парой строк выше. в чем смысл? руби ООП язык, используй объекты, чтобы сохранять и переиспользовать данные

2022-05-02 19:07 UTC, iakkivr commented on db/seeds.rb
> +  author_id = User.pluck(:id).sample
Так прошлый комментарий говорил  о том, что при нескольких накатах сида будут возникать ошибки. При запросе к бд я буду получать список всех id в базе, а при сохранении данных сида - использовать только вновь созданные данные.

2022-05-03 16:46 UTC, BubuntuClu approved these changes

2022-05-03 16:46 UTC, BubuntuClu commented on db/seeds.rb
> +  author_id = User.pluck(:id).sample
не понял твой комментарий)

сейчас ты делаешь так: создаешь пользователя в БД. создаешь тест в БД, но чтобы получить автора, ты лезешь в БД за тем чтобы узнать какого пользователя только что создал и взять его id.
вместо этого ты можешь сделать так: создал пользователя в БД и **так же сохранил созданного пользователя в объект**. создаешь тест в БД и используешь объект с сохраненным пользователем( так ты лишний раз не ходишь в БД за данными). 

представь что подобный код будет в приложении, а не в сидах. при каждой загрузке страницы, ты будешь делать 1-2 запроса за повторными данными, это будет отнимать ресурсы сервера и создавать лишнюю нагрузку на БД. и теперь добавь сюда еще несколько сотен пользователей, которые вместе с тобой грузят эту страницу

2022-05-03 17:41 UTC, iakkivr commented on db/seeds.rb
> +  author_id = User.pluck(:id).sample
Я имел ввиду, что сохраняя созданного пользователя я буду генерировать связи в объектах только среди созданных объектов. А в случае обращения к БД - буду брать все, которые уже записаны. К примеру у меня уже есть 30 юзеров (id 1..30) Вызывая сид я получу юзеров с id (31..40). Далее в сиде при создании тестов я свяжу тесты только с юзерами 31..40, если буду использовать объект для сохранения.

2022-05-07 06:46 UTC, merged